databases:
  - name: limbefoodshare-db
    databaseName: limbefoodshare
    user: limbefoodshare

services:
  - type: web
    name: limbe-food-share
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn foodshare.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: limbefoodshare-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

*.py[cod]
__pycache__/
*.so
*.egg
*.egg-info/
dist/
build/

venv/
env/

*.log
db.sqlite3
db.sqlite3-journal
/staticfiles/
/media/

.env

.vscode/
.idea/
*.swp
*.swo